Some additions i needed in order to make a GUI variant from rtimelog
martinpitt/rtimelog pull request #1
Opened 2022-10-16 18:21 UTC by gwutz

Hi!

I want to contribute a GUI variant for rtimelog. Therefore i needed some slight changes in order to accomplish that. I also tried to remove some `unwrap` so the GUI wont crash.

Sneak peek (no repo yet)
![image](https://user-images.githubusercontent.com/373597/196051624-ce79a7a4-dfa2-4c8b-b160-c23c99004ef6.png)

2022-10-17 05:42 UTC, martinpitt requested changes
Thank you, have fun with adding a GUI! Please don't merge together unrelated changes into a single big commit. This needs to be split up and documented better.

(FTR: I wrote this as a text replacement for gtimelog, so I don't want to merge adding a GUI. But of course I'm happy to change the API to make it easier for your fork)

2022-10-17 05:42 UTC, martinpitt commented on Cargo.toml
> +rustyline = "10.0.0"
Please don't pin down microreleases, just say "10". Any 10.x.y ought to be API compatible. Also, split out the corresponding changes for "update to rustyline 10" into a separate commit.

2022-10-17 05:42 UTC, martinpitt commented on src/activity.rs
> -            // first entry's task is ignored, it just provides the start time
All the changes in this function look like they wouldn't change the behaviour, just change the code style. Please move them into a separate commit, with some rationale (like "Replace unwrap with pattern match because *reason*").

2022-10-17 05:42 UTC, martinpitt commented on src/activity.rs
> +            if let Some(prev) = prev_stop {
Naming this "prev" is confusing here, as in a loop over entries that would intuitively refer to the previous Entry. Name it `prev_stop_time`, or maybe rename the original prev_stop to something else to denote that it's an option.

Also, if you want to make this more robust, then please use `match` instead of `if let`, so that the compiler ensures that the "none" case gets handled as well.

2022-10-17 05:42 UTC, martinpitt commented on Cargo.toml
> +
Please split out the "moved binary" changes into a separate commit.

2022-10-17 05:42 UTC, martinpitt commented on src/store.rs
> +        if let Some(filename) = &self.filename {
Please revert this. If save() ever ends up being called without a file name, this is an internal programming error. Like this, save() would silently succeed without writing a file. If you need this for some purposes, please split out into a separate commit with a rationale, and return an io:Error if self.filename is not set.

2022-10-17 05:42 UTC, martinpitt commented on src/store.rs
> +        let naivenow = NaiveDate::from_ymd(now.year(), now.month(), now.day()).and_hms(now.hour(), now.minute(), now.second());
How is that different from `.naive_local()`? Please split out into a separate commit with a rationale.

2022-10-17 05:45 UTC, martinpitt commented
And of course please [fix the tests](https://github.com/martinpitt/rtimelog/actions/runs/3260446580/jobs/5360087162) :grin:

2022-10-17 16:35 UTC, gwutz commented on src/store.rs
> +        let naivenow = NaiveDate::from_ymd(now.year(), now.month(), now.day()).and_hms(now.hour(), now.minute(), now.second());
The precision between the read entries to the created ones is different because the written entries are getting transformed to lesser precision

2022-10-17 16:36 UTC, gwutz commented on src/store.rs
> +        if let Some(filename) = &self.filename {
Was not sure about that tbh. On one side i didn't wanted to be destructive but on the other side a panic can destroy data too. Reverted

2022-10-17 16:38 UTC, gwutz commented
Thanks for the review Seems like the CI will only run if you approve. Its unfortunate - because if there is something i have to handle i will get the information first if you approved them

2022-10-18 04:57 UTC, martinpitt requested changes
Thanks! The changes are much easier to review now. Please clean up the commit messages to not have over-long lines. A good pattern is a short "Summary: what?" and the "Why?" in the commit message details, i.e. don't squeeze it all into the single-line subject.

> Seems like the CI will only run if you approve. Its unfortunate - 

Sorry, that's GitHub's default behaviour for first-time contributors -- I think to prevent abusing random PRs for crypto mining and such (as you always get up to 6 hours of free compute time). Once your commits are in, CI should run automatically for you.

> because if there is something i have to handle i will get the information first if you approved them

It's just `cargo test`. Now the unit tests actually succeeded, the [current test run](https://github.com/martinpitt/rtimelog/actions/runs/3266917156/jobs/5379605132) failed on `cargo rustc --release -- -Dwarnings`. This is apparently related to the "split out lib" commit, and that command line in .github/workflows/tests.yml needs some adjustment? I don't have an off-hand advice how to fix that.

Thank you!

2022-10-18 04:57 UTC, martinpitt commented on src/activity.rs
> -use chrono::{prelude::*, Duration, NaiveDateTime};
Please wrap the commit message at 80 characters.

Agreed about avoiding unwrap(). This was my learning project :sweat_smile: What additional linter do you use? I currently use clippy and rustfmt, both in vim ale and in CI. Neither complain about the unwrap.

2022-10-18 04:57 UTC, martinpitt commented on src/activity.rs
> +                    continue;
Unnecessary continue

2022-10-18 19:55 UTC, gwutz commented on src/activity.rs
> -use chrono::{prelude::*, Duration, NaiveDateTime};
For sanity checks i use `cargo clippy -- -Dclippy::pedantic` which also shows some unnecessary things but checks for unwraps things which can be helpful from time to time

2022-10-19 15:13 UTC, martinpitt commented
(still needs fixing the "build release mode" step)

2022-10-20 05:20 UTC, martinpitt commented
I fixed the release build check, and some grammar/stylistic issues in the commit messages, and a [rustfmt error](https://github.com/martinpitt/rtimelog/actions/runs/3286978496/jobs/5415655848). You didn't allow pushing to your branch, so I pushed the branch to origin. [Tests succeeded](https://github.com/martinpitt/rtimelog/actions/runs/3286997412/jobs/5415695576), so I landed this in main.

Thank you!

2022-10-20 05:20 UTC, closed without merging