Use XDG Base Directory Specification for config and data files
martinpitt/rtimelog pull request #3
Opened 2022-11-23 20:24 UTC by kebeda

Addresses issue #2.

2022-11-24 09:15 UTC, martinpitt requested changes
Thank you for pointing this out and working on this! I'm really glad to move my files over, non-XDG programs are just annoying. Let's please just simplify the implementation of this, adding integration tests for all possible combinatorial explosions here would be quite annoying, and they are also IMHO undesirable.

2022-11-24 09:15 UTC, martinpitt commented on src/store.rs
> +static HOME_DIR: Lazy<PathBuf> = Lazy::new(|| dirs::home_dir().unwrap());
Pulling in a new crate (once-cell) just for this feels overkill to me, and there is also no need to make these global. Let's just move them to get_legacy_config_dir() and get_data_dir()?

2022-11-24 09:15 UTC, martinpitt commented on src/store.rs
> +        let home_dir = match env::var_os("GTIMELOG_HOME") {
There are about four users of rtimelog in the world. Given how expensive it is to support `$GTIMELOG_HOME`, and nobody asked for it so far, would you be okay with dropping this? That's exactly what `$XDG_DATA_DIRS` etc. fixes in a more general way. Then we can drop get_legacy_config_dir() and also expand_tilde().

2022-11-24 09:15 UTC, martinpitt commented on src/store.rs
> +        let mut log_path = Self::expand_tilde(Self::get_data_dir()).unwrap();
IMHO it's not Rust's or any application's job to expand tildes. That's a shell thing, and explicit `$XDG_*` values are not supposed to contain tildes. At least https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html doesn't mention them, and TBH I'm not interested in propagating that would be a good idea. Dropping this would massively simplify the patch here.

2022-11-24 14:34 UTC, kebeda commented on src/store.rs
> +static HOME_DIR: Lazy<PathBuf> = Lazy::new(|| dirs::home_dir().unwrap());
You already had a transitive dependency on once-cell, I just made it explicit. Regardless, I agree, it does nothing to make these global, especially since they are used exactly once, and it's much easier to read now, commit: ee9e1fd

2022-11-24 15:09 UTC, kebeda commented on src/store.rs
> +        let home_dir = match env::var_os("GTIMELOG_HOME") {
No problem. I originally put that in because that is how [gtimelog still works today](https://github.com/gtimelog/gtimelog/blob/aaecc07b0c2f14055dd55aea6fab7401782cd8bb/src/gtimelog/settings.py#L53), but I'm ok with dropping it. I did leave the check for the "legacy" `~/.gtimelog` in order to not disrupt people who were already using this, didn't want them to force them to make any changes, commit: edda565

2022-11-24 15:11 UTC, kebeda commented on src/store.rs
> +        let mut log_path = Self::expand_tilde(Self::get_data_dir()).unwrap();
Done, commit: edda565.

2022-11-24 15:16 UTC, kebeda commented
Thank you for your consideration, and for publishing this in the first place. I believe your comments have greatly simplified the implementation while still achieving the goals.

2022-11-25 15:27 UTC, martinpitt approved these changes
Very cool, thank you! This works really well, I moved my files to the right XDG place. Yay, one less cluttering directory! :+1: 

I'll squash your commits on landing. Very nice emojis, though :wink:

2022-11-25 15:27 UTC, merged

2022-11-25 15:37 UTC, martinpitt commented
I just tagged a new release [version 4](https://github.com/martinpitt/rtimelog/releases/tag/4), as that's really useful! Unfortunately github is currently having a problem, so the binaries don't get built. I'll try again tomorrow.

2022-11-26 00:23 UTC, kebeda commented
> Very cool, thank you! This works really well, I moved my files to the right XDG place. Yay, one less cluttering directory! +1
> 
> I'll squash your commits on landing. Very nice emojis, though wink

Works great for me too! Check out: https://gitmoji.dev/