Fix week calculation and slack items
martinpitt/rtimelog pull request #5
Opened 2022-12-02 14:49 UTC by kebeda

Continuation of PR #4, adds the "`Time left at work`" and "`At office today`" metrics.

Also fixes a couple of bugs both latent and introduced with the last PR (see each commit for the specifics).

This breaks two unit tests, which I haven't figured a good way to resolve yet. Run `cargo test` to see what I mean. I also introduced a dev-dependency to pretty-assertions to more easily see why a unit test is failing. Any advice on how to resolve this would be appreciated.

2022-12-06 10:12 UTC, martinpitt commented
@kebeda : Not sure if you saw the [failing tests](https://github.com/martinpitt/rtimelog/actions/runs/3602681906/jobs/6069942989)? Thanks for your work here!

2022-12-06 10:12 UTC, martinpitt commented
Ah, of course you did, you mentioned in the description.

2022-12-06 10:22 UTC, martinpitt requested changes
Thanks! If I can talk you into dropping the extra metrics, then the test question solves itself.

2022-12-06 10:22 UTC, martinpitt commented on src/activity.rs
> +            "Time left at work: {} h {} min (till {})",
TBH I've never quite liked these "left at work/at office" messages. I don't want to be told that, and it adds more clutter to the screen. How badly do you want these? I'd really rather not have them in rtimelog..

2022-12-06 10:22 UTC, martinpitt commented on src/store.rs
> +        Local::now().format("%A, %F (week %W)").to_string()
Please split this out into a separate commit, it's unrelated to the week date calculation.

2022-12-06 10:22 UTC, martinpitt commented on src/activity.rs
> +                    if entry.task.contains("**") && !entry.task.contains("***") {
I thought that it's a feature/definition that a "slack" marker `**`  has to be on the beginning of the line. But I don't mind `contains` that much, at least I don't usually have tasks that contain "**". Still, feels conceptually sloppy.

What is `***` now?

2022-12-06 10:22 UTC, martinpitt commented on src/activity.rs
> +        let time_left_at_work_modifier = if time_left.num_minutes() < 0 {
This fixes changes from the previous commit (which I don't like), and shouldn't be in this commit. Can you please rebase this?

2022-12-06 10:22 UTC, martinpitt commented on src/activity.rs
> +                        // NOP
Same, please don't mix fixups of previous commits into later commits, this needs some rebasing.

2022-12-06 10:22 UTC, martinpitt commented on src/activity.rs
> +Time left at work: 0 h 0 min (should've finished at 16:05)
Please squash test changes into the commit that changed it. Every commit should be self-consistent and pass tests by itself, otherwise you break things like `git bisect`, cherry-picking, reverting, etc.

2022-12-06 15:22 UTC, kebeda commented on src/activity.rs
> +            "Time left at work: {} h {} min (till {})",
This is, of course your project. As you wish, I will remove these metrics.

2022-12-06 15:55 UTC, kebeda commented on src/activity.rs
> +                    if entry.task.contains("**") && !entry.task.contains("***") {
From the [gtimelog docs](https://gtimelog.org/docs.html):
> To indicate which activities are not work related add two asterisks to the activity name:
>    `lunch **`
>    `browsing slashdot **`
>    `napping on the couch **`
> If you want some activity (or non-activity) to be completely omitted from the reports, use three asterisks:
>    `break ***`

It doesn't say specifically _where_ the double/triple asterisks should occur, just that they should be in the activity name.

2022-12-06 17:09 UTC, kebeda commented
I'm not very familiar with GitHub, I couldn't figure out how to change the branch on which the PR was based;  so I made the changes you requested to the existing branch via rebasing and then force-pushed the whole thing back up (I'm also allergic to force-pushing anything, but couldn't see any other way to do it). The branch should just now be: main -> 36b158b -> dd4a628 -> 68ed5a9 -> e05d8a9. I hope this is acceptable to you - if not I think I'm going to need some instruction on how to rectify it. Any, with the metrics removed, it is now mostly a bug fix branch...

2022-12-09 06:20 UTC, martinpitt commented
> I'm not very familiar with GitHub, I couldn't figure out how to change the branch on which the PR was based;

You don't need to do that -- PRs always go against origin/main. What you usually do is `git rebase -i origin/main`, and then move/edit/squash around.

Force pushes happen a lot in PRs and branches -- it's fine to get a clean series of patches that are consistent and reviewable, no reason to be afraid of them. If you mess up, there's always `git reflog` for being able to go back to the previous state :grin:

2022-12-09 06:32 UTC, martinpitt approved these changes
Excellent, thank you! I retitled the PR a bit for future archaeology, but it's not very important - it doesn't appear in git log.

2022-12-09 06:32 UTC, martinpitt commented on src/store.rs
> +        Local::now().format("%A, %F (week %W)").to_string()
This is a good change for me as a German. This is fine for now of course, I'm just a bit disappointed that there [doesn't seem to be a format](https://docs.rs/chrono/latest/chrono/format/strftime/index.html) for "use the locale to look up when the week starts"..

2022-12-09 06:32 UTC, martinpitt commented on src/activity.rs
> +                    if entry.task.contains("**") && !entry.task.contains("***") {
Thanks! Let's go with `contains("**")`  then, as you did.

2022-12-09 06:32 UTC, merged